cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^search$', views.product_search, name='product_search'),
    url(r'^pay$', views.pay, name='shop_pay'),
    url(r'^garant$', views.garant, name='shop_garant'),
    url(r'^delivery$', views.delivery, name='shop_delivery'),
    
]

web_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='order')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='Количество', widget=forms.TextInput(attrs={'id':'quantityInp','value':1,'pattern':'[0-9]*'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Корзина покупок
{% endblock %}
{% block content %}
<div class="container">
    <h1>Корзина покупок</h1>
    <div class="cart__detail">
    {% if cart|length == 0 %}
    <div class="cart__empty">
        <h2 class="cart__empty_headline">Корзина пуста :(</h2>
        <div class="cart__empty_img">
            <img src="{% static "./img/shopping-cart.png" %}" alt="">
        </div>
        <a href="{% url "shop:product_list" %}" class="cart__shop">Продолжить покупки</a>
    </div>
    {% else %}
        <div class="cart__item_list">
            {% for item in cart %}
            {% with product=item.product %}
            <div class="cart__item">
                <div class="cart__item_img">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="
                            {% if product.get_title_image %}
                                {{ product.get_title_image.image.url }}
                            {% else %}
                                {% static "img/no_image.png" %}
                            {% endif %}">
                    </a>
                </div>
                <div class="cart__item_name">
                    {{ product.name }}
                </div>
                <div class="cart__item_quantity">
                    {{ item.quantity }}
                </div>
                <div class="cart__item_cost">
                    <p>Стоимость: {{ item.total_price }}р.</p>
                    <p>Цена за штуку: {{ item.price }}р.</p>
                </div>
                <a class="cart__item_remove" href="{% url "cart:cart_remove" product.id%}">x</a>
            </div>
            {% endwith %}
            {% endfor %}
        </div>
        <div class="cart__details">
            <div class="cart__total">
                <h5>Сумма: {{ cart.get_total_price }}</h5>
            </div>
            <a href="{% url "shop:product_list" %}" class="cart__shop">Продолжить покупки</a>
            <a href="{% url "orders:order_create" %}" class="cart__order">
                Оформить заказ
            </a>
        </div>
        {% endif %}
        </div>
    </div>
    {% endblock %}