cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^search$', views.product_search, name='product_search'),
    url(r'^pay$', views.pay, name='shop_pay'),
    url(r'^garant$', views.garant, name='shop_garant'),
    url(r'^delivery$', views.delivery, name='shop_delivery'),
    
]

web_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='order')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
# import ValidationError
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to='categories/', blank=True)
    parent = models.ForeignKey('self', blank=True, null=True, related_name="children", on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        unique_together = ('slug', 'parent',)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                    args=[self.slug])
    def get_sub_categories(self):
        return Category.objects.filter(parent=self)

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    # image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    product_information = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товар'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

    def get_title_image(self):
        if ProductImage.objects.filter(product=self).count() > 0:
            return ProductImage.objects.filter(product=self)[0]

    def get_images(self):
        return ProductImage.objects.filter(product=self)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, default=None, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q,CharField
from django.db.models.functions import Lower
from .models import Category, Product, ProductImage
from promo.models import PromoBaner, PromoSlider
from cart.forms import CartAddProductForm

# Create your views here.

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    baner = PromoBaner.objects.all()[0]
    slider = PromoSlider.objects.all()[0]

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(Q(category=category) | Q(category__parent=category))
    else:
        products = products[:12]
    return render(request, 'shop/product/list.html', {'category':category,
                                                    'categories':categories,
                                                    'products':products,
                                                    'baner':baner,
                                                    'slider':slider,
                                                    })

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form':cart_product_form})

def product_search(request):
    category = None
    query = request.GET.get('q')
    categories = Category.objects.all()
    products = Product.objects.filter(Q(name__icontains=query) | Q(category__name__icontains=query))
    return render(request, 'shop/product/search.html', {'category':category,
                                                    'categories':categories,
                                                    'products':products})

def pay(request):
    return render (request, 'shop/pay.html',{})

def garant(request):
    return render (request, 'shop/garant.html',{})

def delivery(request):
    return render (request, 'shop/delivery.html',{})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Интернет магазин | MobiStore{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link href="{% static "css/shop.css" %}" rel="stylesheet">
    <link href="{% static "css/cart.css" %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <meta name="keywords" content="Мобисторе, моби сторе, моби стори, мобе сторе, мобе стори, mobistore, mobi store, мобильные телефоны купить, ноутбук купить, бытовая техника купить, донецк, bq купить донецк, bq, xiaomy купить">
    <meta name="description" content="Магазин MobiStore предлагает более 500 видов техники и аксессуаров по доступной цене, с возможностью самовывоза и доставки. Безналичная и наличная оплата.">
</head>
<body>
<div class="navbar">
    <div class="container">
        <ul class="nav-list">
            <li class="nav-item"><a href="{% url "shop:shop_garant" %}" class="nav-link">Гарантия</a></li>
            <li class="nav-item"><a href="{% url "shop:shop_delivery" %}" class="nav-link">Доставка</a></li>
            <li class="nav-item"><a href="{% url "shop:shop_pay" %}" class="nav-link">Оплата</a></li>
        </ul>
        <form action="#">
            <button class="auth_btn"><img src="{% static "img/ico_user.png" %}" alt="">  Авторизация</button>
        </form>
    </div>
    
</div>
<div id="header">
    <div class="container">
        <a href="/" class="logo"><img src="{% static "img/logo.png" %}" alt=""></a>
        <a href="" class="adress"><img src="{% static "img/ico_map.png" %}" alt=""> Полоцкая улица, 1Г, Донецк</a>
        <p class="time"><img src="{% static "img/ico_clock.png" %}" alt=""> Пн-пт: 9:00 - 19:00 <img src="{% static "img/ico_clock.png" %}" alt=""> Сб-вс: 9:00 - 19:00</p>
        <p class="phone">
            +38(071)3389708 <br>
            <a href="#" class="write_us_triger" >Заказать звонок</a>
        </p>
    </div>
</div>
<div id="subheader">
    <div class="container">
        <div class="catalog">
            <span class="catalog__burger"></span>
            <span class="catalog__title">Каталог товаров</span>
            <span class="catalog__wrapper"></span>
            <ul class="categories__list">
                {% for c in categories %}
                    {% if c.parent == None %}
                        <li class="categories__item  {% if c.get_sub_categories %}parent{% endif %}">
                            <a href="{{c.get_absolute_url}}" class="categories__link">{{c.name}}</a>
                            {% if c.get_sub_categories %}
                                <div class="categories__item_subs">
                                    {% for sub_c in c.get_sub_categories %}
                                        <div class="categories__item_sub">
                                            <a href="{{sub_c.get_absolute_url}}">
                                                <img class="categories_sub_img" src="{% if sub_c.image %}{{ sub_c.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                                            </a>
                                            <a href="{{sub_c.get_absolute_url}}">{{sub_c.name}}</a>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <form class="search_form" action="{% url "shop:product_search" %}">
            <img class="search_form__icon" src="{% static "./img/ico_search.png" %}" alt="">
            <input class='search_input' placeholder="Найдите свои товары здесь" name='q' type="text">
        </form>
        <div class="cart_bar">
            <a href="{% url "cart:cart_detail" %}">
                {% with total_items=cart|length %}
                    <div class="cart_bar__icon">
                        <img src="{% static "./img/ico_shop.png" %}" alt="">
                        <span class="cart_bar__counter">{{ total_items }}</span>
                    </div>
                        {{ cart.get_total_price }}руб.
                {% endwith %}
            </a>
        </div>
    </div>
</div>
    {% block content %}
    {% endblock %}
</div>
<footer>
    <div class="container">
        <div class="footer__main">
            <div class="footer__col contacts">
                <p class="contacts__phone">+38(071)3389708</p>
                <button class="contacts__write_us write_us_triger">Написать нам</button>
                <p><a class="adress" href="#">Полоцкая улица, 1Г, Донецк</a></p>
            </div>
            <div class="footer__col info">
                <h4>Информация:</h4>
                <ul class="info_list">
                    <li class="info_item"><a href="#" class="info_link">Гарантия</a></li>
                    <li class="info_item"><a href="#" class="info_link">Доставка</a></li>
                    <li class="info_item"><a href="#" class="info_link">Оплата</a></li>
                    <li class="info_item"><a href="#" class="info_link">Контакты</a></li>
                </ul>
            </div>
            <div class="time">
                <h4>Время работы:</h4>
                <p class="time_clock"><img src="{% static "img/ico_clock.png" %}" alt=""> Пн-пт: 9:00 - 19:00</p>
                <p class="time_clock"><img src="{% static "img/ico_clock.png" %}" alt=""> Сб-вс: 9:00 - 19:00</p>
                <h4>Мы в социальных сетях</h4>
                <div class="socials">
                    <a href="https://vk.com/mobistore_dn" class="">
                        <img src="{% static "img/ico_vk.png" %}" alt="вк">
                    </a>
                    <a href="https://www.instagram.com/mobistore_donetsk" class="">
                        <img src="{% static "img/ico_inst.png" %}" alt="инстаграмм">
                    </a>
                </div>
            </div>
            <div class="logo">
                <a href="/" class="logo"><img src="{% static "img/logo.png" %}" alt=""></a>
            </div>
        </div>
    </div>
    <div class="footer__copyrights"><p>MobiStore 2021 Все права защищены. Разработано <a href="http://sos-computer.site">Сос Компьютер</a></p></div>
</footer>
<div class="modal__form">
    <div class="modal__content">
        <div class="modal__header">
            <h2>Обратный звонок</h2>
            <button class="modal__close_btn">
                <span class="modal__close_icon"></span>
            </button>
        </div>
        <div class="modal__body">
            <form>
                <input type="text" placeholder="Ваше имя" name='name'>
                <input type="text" placeholder="Ваш телефон" name='phone'>
                <div class="perc_rights_block">
                    <input type="checkbox" id="perc_rights" name='license'><label for="perc_rights" >Я прочитал <a href="#">Политика безопасности</a> и согласен с условиями</label>
                </div>
                {% csrf_token %}
                <button>Отправить</button>
            </form>
        </div>
    </div>
</div>
<script>
    let modalForm = document.querySelector('.modal__form');
    let modalClose = document.querySelector('.modal__close_btn');
    let modalBtns = document.querySelectorAll('.write_us_triger')
    modalBtns.forEach(function(btn){
        btn.addEventListener('click',function(){
            modalForm.style.display = 'block';
        })
    })
    modalClose.addEventListener('click',function(e){
            modalForm.style.display = 'none';
    })
    modalForm.addEventListener('click',function(e){
        if(e.target == modalForm){
            modalForm.style.display = 'none';
        }
    })
    modalForm.querySelector('form').addEventListener('submit',async function(e){
        e.preventDefault();
        formData = new FormData(modalForm.querySelector('form'))
        //data.append('csrfmiddlewaretoken', $('#csrf-helper input[name="csrfmiddlewaretoken"]').attr('value'));
        console.dir(formData)
        let response = await fetch('./orders/create_request/', {
        method: 'POST',
        body: formData,
        credentials: 'same-origin',
        });

        let result = await response.json();
        if(result.status == true){
            modalForm.style.display = 'none';
        }
        alert(result.text)

    })
</script>
</body>
</html>

shop/templates/shop/delivery.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Доставка
{% endblock %}
{% block content %}
    <div id="main" class="shop_info">
        <div class="container">
        <h1>Оплата</h1>
            <div class="shop_info_description">
                <h4 class="description_title">Доставка:</h4>
                <h4 class="description_title">- СТОИМОСТЬ ДОСТАВКИ</h4>

                <p>Бесплатная курьерская доставка по Донецку и Макеевке  при заказе от 15,000 рублей 
                    При заказе менее 15,000 рублей доставка от 200 рублей</p>
                <br>
                <h4 class="description_title">- СРОКИ ДОСТАВКИ</h4>

                <p>Сроки доставки заказа зависят от наличия товаров на складе. Если в момент оформления заказа все выбранные товары есть в наличии, то мы доставим заказ в течение 1-2 дней. Если заказываемый товар отсутствует на складе, то доставка будет осуществлена после получения товара, и согласования срока с клиентом.</p>
                <br>
                <h4 class="description_title">- АДРЕС ПУНКТА САМОВЫВОЗА:</h4>
                <p>Полоцкая улица, 1Г, Донецк | Телефон: +38(071)3389708</p>
                <p>График работы: с 9:00 до 19:00</p>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/garant.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Гарантия
{% endblock %}
{% block content %}
<div id="main" class="shop_info">
    <div class="container">
        <h1>Оплата</h1>
        <div class="shop_info_description">
            <h4 class="description_title">Условия возврата:</h4>
            <p>Для оформления возврата возьмите с собой паспорт, чек и товар в упаковке.</p>

            <p>Мы вернем вам деньги в день возврата товара или, в случае отсутствия денег в кассе, не позже чем через 7 дней.</p>

            <p>Мы оформляем возврат, если:</p>

            <ul>
                <li>товар не был в употреблении и не имеет следов использования: царапин, сколов, потёртостей, на счётчике телефона не более 5 минут разговоров, программное обеспечение не подвергалось изменениям;</li>
                <li>товар полностью укомплектован и не нарушена целостность упаковки;</li>
                <li>сохранены все ярлыки и заводская маркировка.</li>
            </ul>
<p>Если товар не работает, обмен или возврат товара производится только при наличии заключения сервисного центра, авторизованного производителем, о том, что условия эксплуатации не нарушены.</p>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/pay.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Оплата
{% endblock %}
{% block content %}
    <div id="main" class="shop_info">
        <div class="container">
        <h1>Оплата</h1>
            <div class="shop_info_description">
                <ul>
                    <li>Оплата при получении наличными</li>
                    <li>Онлайн-оплата картой Visa / Mastercard</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}